apiVersion: apps/v1
kind: Deployment
metadata:
  name: kimo-cloudstorage-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kimo-sbucket
  template:
    metadata:
      labels:
        app: kimo-sbucket
    spec:
      serviceAccountName: kube-sa
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
        - name: kimo-py-container
          image: gcr.io/sandbox-io-289003/my-py-app
          ports:
            - containerPort: 8080